'use strict'

module.exports = { resume: '재개하다, 다시 시작하다',
  applicant: '지원자, 신청자',
  requirement: '필요조건, 요건',
  meet: '(필요,요구 등을)만족시키다',
  qualified: '자격있는, 적격의',
  candidate: '후보자, 지원자',
  confidence: '확신, 자신, 신임',
  highly: '매우, 대단히',
  professional: '전문적인, 직업의, 전문가',
  interview: '면접, 면접을 보다',
  hire: '고용하다',
  training: '교육, 훈련',
  reference: '추천서, 참고',
  position: '일자리, 직책, 두다',
  achievement: '성취, 달성',
  impressed: '인상 깊게 생각하는, 감명을 받은',
  excellent: '훌륭한',
  eligible: '자격이 있는, 적격의',
  identify: '알아보다, 확인하다',
  associate: '관련시키다',
  condition: '조건',
  employment: '고용',
  lack: '~이 없다, 부족',
  managerial: '관리의',
  diligent: '성실한',
  familiar: '익숙한, 친숙한',
  proficiency: '숙달, 능숙',
  prospective: '장래의, 미래의',
  appeal: '관심을 끌다, 매력적이다',
  specialize: '~을 전공하다, 전문적으로 다루다',
  apprehensive: '걱정하는, 염려하는',
  consultant: '고문, 컨설턴트',
  entitle: '자격을 주다',
  degree: '학위',
  payroll: '임금대장, 금료명부',
  recruit: '(신입사원등을)모집하다',
  certification: '증명서, 증명',
  occupation: '직업',
  wage: '임금, 급료',
  attire: '복장, 옷차림새',
  code: '규범, 관례;암호',
  concern: '우려, 걱정, 문제, 일, ~을 걱정스럽게 하다; 영향을 미치다, 관련되다.',
  policy: '규정; 보험, 증권',
  comply: '준수하다, 따르다',
  regulation: '규정',
  exception: '예외',
  adhere: '지키다, 고수하다',
  severely: '엄격하게, 심하게',
  refrain: '자제하다, 삼가다',
  permission: '허락, 허가',
  access: '이용권한, 접근;통로, ~에 접근하다, 도달하다',
  thoroughly: '철저하게, 완전히, 대단히',
  revise: '(의견, 계획을)수정하다, 변경하다',
  approach: '접근법, 처리방법',
  approval: '승인, 인가',
  form: '종류, 유형, 양식',
  immediately: '즉시, 곧',
  inspection: '점검, 검사',
  arrangement: '준비, 마련, 주선',
  procedure: '절차',
  negative: '부정적인, 비관적인',
  mandate: '명령하다, 지시하다, 권한, 지시, 명령',
  effect: '(법률등의)효력, 효과, 영향, 결과로서 ~을 가져오다',
  drastically: '심하게, 과감하게, 철저하게',
  'according to': '~에 따라',
  enable: '(무엇을)가능하게 하다',
  standard: '기준, 표준',
  constant: '지속적인, 끊임없이 계속하는',
  act: '법령, 결의서; 행위, 행동, 결정하다, 판결을 내리다, 행동하다',
  compensation: '보상금, 보상',
  ban: '금지, 금지하다',
  obligation: '의무, 책임',
  authorize: '~을 인가하다, 권한을 부여하다.',
  prohibit: '금지하다',
  abolish: '(제도, 법률등을)폐지하다',
  enforce: '(법률을)시행하다, 집행하다',
  habit: '습관, 버릇',
  lagislation: '법률, 법규',
  restrict: '한정하다, 제한하다',
  accustomed: '익숙한',
  corporatiion: '주식회사, 법인',
  demanding: '요구가 많은, 힘든',
  colleague: '동료',
  division: '부서',
  request: '요청, 요청하다',
  efficiently: '효율적으로',
  manage: '~을 경영하다; 가까스로 하다',
  submit: '제출하다',
  directly: '곧바로',
  remind: '~에게 상기시키다, 일깨우다',
  instruct: '지시하다, 가르치다',
  deadline: '마감일, 마감 시간',
  sample: '견본, 샘플, 표본\r\n시식하다, (견본으로 질을)시험하다',
  notify: '~에게 통지하다, 알리다',
  perform: '행하다, 실행하다',
  monitor: '감독하다, 감시하다, 실행하다',
  deserve: '~할 만하다, ~할 가치가 있다',
  assignment: '일, 임무, 과제',
  entire: '전체의',
  release: '발표하다, 공개하다, 출시, 발매',
  extension: '연장, 연기; (전화의)내선',
  electronically: '컴퓨터 통신망으로, 컴퓨터로',
  attendance: '출석, 출근',
  absolutely: '절대적으로, 완전히',
  delegate: '(권한등을)위임하다. 대표',
  attentively: '주의 깊게, 조심스럽게',
  supervision: '감독',
  workshop: '워크숍, 연수',
  draw: '끌다, 끌어당기다',
  revision: '수정, 개정',
  reluctantly: '마지못해, 꺼려하여',
  acquaint: '~에게 숙지시키다, 잘 알게 하다',
  convey: '(용건을)전달하다',
  check: '검사하다, 조사하다, 확인하다',
  headquarters: '본부',
  file: '(서류를)정리하다, 철하다;\r\n(서류, 신청, 고소 등을)정식으로 제기하다, 제출하다',
  oversee: '감독하다 (foresee예견하다, oversea해외의)',
  involved: '관여하는, 관계된, 연루된',
  concentrate: '집중하다, 집중시키다',
  lax: '(행동 등이)느슨한, 규율에 못 미치는',
  procrastinate: '미루다, 꾸물거리다',
  combined: '결합된, 합동의',
  accomplish: '성취하다',
  voluntarily: '자발적으로',
  undertake: '(일을)떠맡다',
  assume: '(증거는 없으나)사실이라고 생각하다;\r\n(책임,역할을)맡다',
  occasionally: '가끔, 때때로',
  employee: '직원, 고용인',
  assist: '돕다, 조력하다',
  satisfied: '만족하는, 만족스러워하는',
  manner: '방식, 태도',
  responsible: '책임이 있는, 책임져야 할',
  conduct: '(업무 등을)수행하다',
  adjust: '적응하다',
  personnel: '(집합적)직원, 인원; 인사과',
  agree: '동의하다',
  supervise: '감독하다, 지도하다',
  coworker: '동료, 협력자',
  direct: '~에게 길을 안내하다, 가르쳐 주다',
  confidential: '기밀의, 내밀한',
  assign: '배정하다, 할당하다',
  leading: '선도적인, 일류의, 가장 중요한, 선두적인',
  formal: '격식을 갖춘',
  remove: '해임하다, 제거하다',
  collect: '모으다',
  coordinate: '조정하다',
  hardly: '거의~하지않다',
  abstract: '추상적인, 막연한',
  directory: '주소록',
  accountable: '책임이 있는',
  skillfully: '능숙하게, 솜씨있게',
  exclusive: '독점적인, 배타적인',
  intention: '의지, 의향',
  transform: '바꾸다, 변모시키다',
  respectful: '정중한, 존중하는',
  duplicate: '사본',
  contrary: '반대',
  disturbing: '충격적인, 불안감을 주는, 방해하는',
  engage: '관여하다, 종사하다',
  foster: '촉진하다, 육성하다',
  neutrality: '중립성, 중립',
  widely: '널리',
  sophisticated: '(기계가)정교한, 복잡한; 세련된',
  timely: '시기적절한, 때를 맞춘',
  realistically: '현실적으로',
  promptly: '즉시; 정각에',
  accessible: '출입할 수 있는; 이용할 수 있는',
  implement: '실시하다, 실행하다',
  feedback: '의견, 반응',
  outstanding: '우수한; (부채 등이)미지불된',
  inform: '~에게 알리다',
  replacement: '교체, 후임자',
  announcement: '공고, 발표',
  department: '(조직, 기구의)부서',
  permanently: '영구적으로, 불변으로',
  fulfill: '(조건을)만족시키다, (약속, 의무등을)지키다, 이행하다',
  outline: '개요, 설명하다, 약술하다',
  explain: '설명하다',
  contain: '포함하다',
  compile: '(자료 등을)편집하다; 모으다',
  subsequent: '차후의, 그 다음의',
  overview: '개요, 개관',
  provider: '공급자, 제공자',
  matter: '문제, 일',
  expertise: '전문지식, 전문기술',
  demonstrate: '증명하다; (모형, 실험등으로)설명하다',
  remainder: '나머지',
  essential: '필수적인, 극히 중요한, 본질적인',
  divide: '분배하다, 나누다',
  major: '주요한, 중대한',
  compliance: '(명령, 법규에의)준수',
  clarify: '명확하게 하다',
  face: '(문제 등에)직면하다; 향하다, 마주보다',
  follow: '~을 따라가다; 주시하다; (분명히)이해하다',
  aspect: '관점, 국면',
  apparently: '보기에 ~한 듯한, 외관상으로는',
  aware: '알고 있는, 인식하고 있는',
  extended: '(기간 등을)연장한, 장기간에 걸친',
  accidentally: '뜻하지 않게, 우연히',
  advisable: '바람직한, 합당한',
  concerned: '염려하는, 걱정하는; 관련된',
  speak: '이야기 하다',
  collection: '소장품, 수집물; 징수, 수금',
  exhibition: '전시회',
  celebrity: '유명인사, 명사',
  live: '(라디오, TV가)생방송인',
  improvise: '(연주, 연설 등을)즉흥적으로 하다, 즉석에서 만들다.',
  popular: '인기있는',
  donation: '기증, 기부',
  alumni: '동창생들, 졸업생들',
  present: '제시하다, 현재의, 참석한',
  admission: '입장',
  banquet: '연회, 만찬',
  anniversary: '기념일',
  required: '필수의, 의무적인',
  succeed: '성공하다, 뒤를 잇다',
  rest: '쉬다,휴식, 나머지',
  'fund-raising': '모금',
  issue: '(출판물의)제 ~호; 문제, 쟁점',
  subscription: '(정기발행물의) 구독',
  appear: '나타나다, 출현하다',
  accompany: '동행하다, 동반하다',
  edition: '(간행물의)판',
  specifically: '명확하게, 분명히; 특히, 특별히',
  anonymous: '익명의, 이름을 모르는',
  commit: '헌신하다, 전념하다',
  information: '정보, 자료',
  audience: '청중, 관중',
  author: '작가, 저자',
  note: '주목하다; 특별히 언급하다.',
  antique: '골동품',
  manuscript: '원고',
  beneficial: '유익한, 이로운',
  upcoming: '곧 있을, 다가오는',
  lend: '빌려주다',
  current: '현재의,; 현행의, 통용되는',
  local: '지방의, 고장의',
  variety: '다양성, 변화',
  advocate: '옹호자',
  contributor: '기고가, 공헌자',
  defy: '저항하다; (설명,묘사등이)거의 불가능하다',
  fascinating: '매혹적인, 황홀한',
  showing: '(영화, 연극의)상영; 전시',
  survey: '설문조사',
  analysis: '분석',
  respondent: '응답자',
  competition: '경쟁',
  consistently: '항상, 일관되게',
  demand: '수요, 요구하다',
  'do one\'s utmost': '전력을 다하다',
  expand: '확장하다, 확대하다',
  advanced: '고급의; 진보한, 앞선',
  postpone: '연기하다, 뒤로 미루다',
  additional: '추가의, 부가적인',
  appreciate: '고맙게 생각하다; 높이 평가하다; 감상하다',
  demonstration: '설명; 드러냄, 시연',
  buy: '사다, 구입하다',
  examine: '조사하다',
  effective: '효과적인; (법률 등이)발표되는, 시행되는',
  like: '좋아하다',
  especially: '특히',
  closely: '면밀히, 엄밀히',
  reserve: '예약하다, 지정하다; 보존하다',
  cooperate: '협력하다, 협동하다',
  very: '매우, 대단히, 아주',
  consecutive: '연속적인',
  expectation: '예상, 기대',
  publicize: '공표하다; 광고하다, 선전하다',
  raise: '높이다, 올리다; (의문을)제기하다',
  extremely: '극도로, 대단히',
  affect: '~에 영향을 미치다, 불리하게 작용하다',
  target: '목표, 목표로 삼다',
  campaign: '운동, 캠페인',
  probable: '개연성이 높은, 유망한',
  focus: '집중시키다, 집중하다',
  seasonal: '계절의, 계절적인',
  impact: '영향, 충격',
  comparison: '비교',
  gap: '격차',
  mounting: '증가하는, 오르는',
  reflective: '반영하는',
  advertisement: '광고',
  marginal: '약간의; 주변의',
  customer: '고객',
  influence: '~에 영향을 주다, 영향',
  instantly: '즉각적으로, 즉시',
  creative: '창조적인, 독창적인',
  aggressively: '적극적으로',
  aim: '~을 겨누다, 목표, 목적',
  strategy: '전략',
  indicate: '보여주다, 나타내다',
  attract: '끌다, 유인하다',
  experience: '경험, 체험, 체험하다, 경험하다',
  analyze: '분석하다, 분석적으로 검토하다',
  introduce: '(신제품을)발표하다, 소개하다',
  advise: '조언해주다, 충고하다',
  subscribe: '구독하다',
  absence: '부재; 결근, 결석',
  means: '방법, 수단',
  prefer: '(다른 것보다)~을 더 좋아하다, 선호하다',
  advantage: '이점, 강점',
  forward: '앞으로, (물건, 정보를)보내다',
  contemporary: '동시대의; 현대의, 당대의',
  discussion: '토론, 토의',
  initial: '처음의, 최초의',
  steadily: '착실하게; 꾸준히',
  necessarily: '반드시',
  resolve: '(문제 등을)해결하다',
  detect: '간파하다, 탐지하다',
  intensify: '강화하다, 증대하다, 강렬하게 만들다.',
  favorably: '호의적으로; 순조롭게',
  cover: '포함하다; 지불하다; 덮다',
  less: '보다 적은, 덜한',
  majority: '대부분, 대다수',
  adopt: '채택하다',
  largely: '주로, 대부분',
  disregard: '소홀히 하다, 무시하다',
  effort: '노력',
  incentive: '혜택, 장려금',
  need: '필요, 요구, 욕구, ~할 필요가 있다.',
  mastermind: '(계획 등의)입안자, 지도자',
  stagnant: '침체된, 불경기의, (stagnance침체, 정체, 불황)',
  dramatically: '극적으로',
  brisk: '활발한, 호황의',
  unstable: '불안정한, 변하기 쉬운',
  rapidly: '급속히, 빨리',
  soar: '(물가 등이)폭등하다, 높이 치솟다',
  assert: '단언하다, 주장하다 (assertion 단언, 주장)',
  boost: '(경기를)부양시키다, 상승시키다',
  analyst: '분석가',
  potential: '잠재적인',
  pleased: '만족해하는, 기쁜',
  remain: '계속~한 상태이다; 아직 ~해야한다',
  limited: '제한된, 한정된',
  costly: '비용이 많이 드는, 손실이 큰',
  particular: '특정한, 독특한, 세심한 (partocularly 특히)',
  drastic: '과감한, 급격한',
  evenly: '고르게, 균등하게',
  evidence: '증거',
  prospect: '전망, 예상 (prospective 장래의, 미래의, 기대되는)',
  lead: '이글다, 지휘하다; (어떤 결과에)이르다',
  fall: '(값, 가치가)하락하다',
  period: '기간, 시기',
  indicator: '지표, 지수',
  industry: '산업',
  likely: '~할 것 같은',
  boom: '붐, 호황',
  director: '임원, 책임자',
  substitute: '대용품, 대신하다(substitution 대용, 대체)',
  consequence: '결과',
  fairly: '상당히, 꽤',
  economical: '경제적인, 절약되는',
  thrive: '번영하다, 성공하다',
  implication: '영향, 밀접한 관계 (implicate 관련시키다, 관련되었음을 나타내다)',
  wane: '감소, 감퇴',
  prosperity: '번영 (prosper 번영하다)',
  depression: '불황 (depress 하락시키다, 약하게하다)',
  dwindle: '줄어들다, 감소되다',
  impede: '저해하다, 방해하다',
  promising: '유망한, 전망이 좋은',
  adversity: '역경, 불운',
  purchase: '구매하다, 구매',
  installment: '할부',
  affordable: '(가격이)알맞은, 감당할 수 있는',
  exactly: '정확히',
  auction: '경매',
  authentic: '진정한, 진짜의, 진품의',
  charge: '요금,청구,금액;책임,의무\r\n~을 청구하다; (외상으로)달아놓다',
  notice: '통지, 공고',
  experienced: '경험이 있는, 노련한, 능숙한',
  instruction: '설명, 지시 (instruct 가르치다, 지시하다, instructor교사, 강사)',
  expert: '전문가, 전문가의, 전문적인',
  warranty: '(품질 등의)보증, 보증서',
  refund: '환불, 환불금',
  subscriber: '가입자, 구독자',
  delivery: '배달',
  price: '가격',
  receipt: '영수증',
  offer: '제공하다, 제공,오퍼',
  carefully: '주의깊게, 신중히',
  benefit: '혜택, 이익, 혜택을 보다, 이익을 얻다',
  exclusively: '오로지, 독점적으로',
  description: '(제품등의)설명, 해설',
  relatively: '상대적으로',
  spare: '아끼다, 할애하다, 예비의, 여분의',
  preparation: '준비, 대비',
  area: '지역, 구역',
  clearance: '정리, 없애기; 허가',
  alter: '(성질, 형상을)고치다, 바꾸다',
  apply: '적용하다; 지원하다',
  mutually: '서로, 상호 간에 (mutuality 상호관계, 상호의존)',
  method: '방식, 방법',
  acceptable: '용인되는, 받아들일 수 있는;\r\n훌륭한, 만족스러운',
  desire: '욕구, 갈망, 원하다, 바라다',
  redeemable: '(현금,상품과)교환할 수 있는, 환급할 수 있는( redeem 상환하다)',
  officially: '공식적으로',
  consumption: '소비(량), 소모 (consumptive 소모적인)',
  qualify: '~의 자격을 얻다',
  fabric: '섬유, 천',
  valid: '유효한',
  vendor: '노점상, 가판대; 판매업체',
  research: '연구, 조사',
  devise: '고안하다, 발명하다',
  revolutionary: '혁명적인',
  innovative: '혁신적인',
  feature: '특징, 특색, 특징으로 삼다, 특별히 포함하다',
  inspiration: '영감',
  sufficiently: '충분히(sufficient 충분한, 충분)',
  patent: '특허, 특허권, 특허품',
  envision: '(장래의 일 등을)계획하다, 상상하다',
  extend: '연장하다; (기간을)늘리다;\r\n(감사의 뜻을)말하다, 베풀다',
  following: '~후에, 다음의, 다음에 오는',
  intend: '~할 작정이다; 의도하다',
  grant: '(인정하여 정식으로)수여하다, 주다,\r\n(연구비, 장학금등의)보조금',
  allow: '~하게 하다, ~을 허락하다',
  inspect: '~을 검사하다, 조사하다',
  improve: '향상시키다, 개선하다',
  increasingly: '점점, 더욱 더',
  invest: '투자하다, 운용하다',
  various: '여러 가지의, 가지각색의',
  upgrade: '업그레이드, 개량형\r\n업그레이드하다, 개선하다',
  manual: '설명서, 안내서',
  explore: '조사하다, 탐구하다',
  response: '응답, 대답',
  appearance: '외관, 외모',
  successful: '성공적인, 성공한',
  hold: '~을 수용하다, ~을 담다;\r\n(회의 등을)개최하다, 열다',
  advance: '진보, 전진',
  reliable: '믿을 만한, 신뢰할 수 있는',
  quality: '품질, 질',
  domestic: '국내의, 국산의',
  development: '개발, 발전',
  availability: '(입수)가능성, 유효성, 유용성',
  update: '갱신, 개정, 갱신하다,\r\n최신의 것으로 하다',
  accurate: '정확한',
  complicate: '복잡한(complicatedly복잡하게)',
  accomplished: '숙련된, 노련한',
  inquiry: '문의, 질문',
  indication: '징후, 조짐',
  manufacturer: '제조회사, 제조업자',
  compatible: '호환되는, 양립할 수 있는(compatibility 양립성, 호환성)',
  superior: '우수한, 상급의',
  absolute: '완전한, 완전무결한',
  broaden: '넓히다',
  corrosion: '부식',
  epuipment: '장비, 설비',
  automate: '자동화하다',
  specification: '명세서, 설명서, 사양',
  properly: '제대로, 정확하게',
  safety: '안전',
  precaution: '예방조치, 예방책',
  operate: '(기계 등이)작동하다, 움직이다',
  processing: '가공, 처리(process 과정, 진행, 처리하다)',
  capacity: '용량, 수용력; 역할',
  assemble: '(부품,기계 등을)조립하다;\r\n(사람을)모으다',
  utilize: '이용하다, 활용하다',
  place: '~을-한 상태에 두다;\r\n(지시,주문,신청등을)하다',
  fill: '~을 채우다; (주문대로)이행하다',
  manufacturing: '제조(업)의',
  renovate: '(낡은 건물, 가구등을)개조하다,\r\n수리하다, 보수하다',
  decision: '결정, 판단',
  material: '재료, 물질',
  success: '성과, 성공',
  attribute: '(원인을)~의 덕분으로 돌리다',
  efficiency: '효율, 능률',
  limit: '한계, 제한',
  tailored: '맞춤의, 주문에 따라 맞춘',
  component: '부품, (구성)요소',
  capable: '~을 할 수 있는, ~할 능력이 있는',
  economize: '절약하다, 아끼다',
  flexible: '융통성 있는; 유연한, 잘 구부러지는',
  comparable: '필적하는, 비교되는',
  produce: '생산하다',
  respectively: '각각, 따로(respective 각각의)',
  device: '장치',
  trim: '(깍아)다듬다, 없애다; 삭감하다',
  launch: '(신제품을)출시하다',
  separately: '개별적으로, 따로따로',
  expiration: '(기간,임기 등의)만료, 만기',
  maneuver: '이동시키다, 움직이다',
  coming: '다가오는',
  damaged: '손상된, 손해를 입은',
  prevent: '~을 막다, ~을 예방하다',
  power: '전력, 전기',
  chemical: '화학제품',
  complaint: '불평',
  deal: '처리하다; 거래하다; 분배하다',
  argumentative: '논쟁적인, 논쟁을 좋아하는',
  appropriately: '적절하게(appropriate 적합한)',
  respond: '응답하다',
  infuriate: '화나게하다, 격분시키다',
  curteous: '예의바른',
  satisfaction: '만족',
  inconvenience: '불편, ~에게 불편을 느끼게 하다',
  complete: '완료하다, 완성하다, 완료된, 완성된',
  specific: '구체적인, 명확한',
  return: '반환하다, 반송하다',
  replace: '~을 교체하다, 대체하다',
  presentation: '발표',
  evaluation: '평가',
  confident: '자신 있는',
  cause: '~을 야기하다, ~의 원인이 되다\r\n원인',
  commentary: '해설, 설명(comment 해설하다,논평, 주석을달다)',
  notification: '통지',
  apologize: '사과하다',
  interact: '소통하다, 교류하다; 상호작용을 하다',
  certain: '확신하는, 확실한; 특정한',
  commitment: '헌신, 전념',
  applaud: '~에게 박수를 보내다; 칭찬하다',
  biography: '약력, 전기',
  critical: '비판적인; 중요한; 위기의',
  'depend on': '~에 달려 있다, ~에게 의존하다',
  combine: '결합시키다',
  priority: '우선권, 우선사항',
  observe: '관찰하다, 주시하다;\r\n(규칙 등을)준수하다, 지키다',
  defective: '결함이 있는',
  reflect: '반영하다, 나타내다',
  attitude: '태도, 마음가짐',
  disappoint: '실망시키다',
  inquire: '문의하다, 질문하다',
  insert: '삽입하다',
  disclose: '공개하다, 드러내다',
  guarantee: '보장하다, 보장',
  politely: '공손하게, 예의바르게',
  seriously: '진지하게',
  international: '국제적인',
  attraction: '관광 명소',
  itinerary: '여행 일정',
  exotic: '이국적인, 매혹적인',
  diverse: '다양한',
  superb: '최고의, 뛰어난',
  baggage: '수화물',
  destination: '목적지',
  missing: '분실된, 없어진',
  locate: '(~의 위치를)찾아내다;\r\n~을 위치시키다',
  approximately: '대략',
  duty: '관세,세금; 직무,의무',
  process: '과정, 처리하다',
  board: '탑승하다, 이사회',
  comfortable: '편안한',
  declare: '(세관에서)신고하다',
  specify: '명시하다 (specification 열거, 명시, 명세서)',
  depart: '출발하다',
  emergency: '비상시, 비상 사태',
  passenger: '승객',
  outgoing: '(장소를)출발하는, 떠나는;\r\n(지위를)떠나는',
  tighly: '단단히, 꽉',
  tour: '(공장,시설 등의)견학, 짧은 여행',
  carrier: '항공사, 수송기, 수송 회사',
  customarily: '관례상, 습관적으로',
  confuse: '혼란시키다 (refuse 거절하다, 거부하다)',
  arrive: '도착하다',
  brochure: '(홍보용)소책자, 브로셔',
  involve: '수반하다, 포함하다; 참여시키다',
  ship: '(배나 다른 운송 수단으로)운송하다, 수송하다, 선박, 배',
  suitcase: '여행가방',
  unavailable: '이용할 수 없는, 구할 수 없는',
  'fill out/in': '(서류에)기입하다, 적어 넣다',
  customs: '세관',
  away: '떨어져서',
  dramatic: '멋진, 극적인; 급격한',
  hospitality: '환대, 친절',
  indulge: '빠지다, 탐닉하다',
  proximity: '가까움, 근접함',
  seating: '(집합적)좌석 설비; 좌석 배열',
  unlimited: '무제한의',
  proposal: '제안, 계획',
  alliance: '동맹, 제휴',
  stipulation: '계약 조건',
  term: '조건; 임기, 기한',
  compromise: '타협, 화해',
  negotiation: '협상, 교섭',
  agreement: '계약, 협정; 합의',
  deadlock: '교착 상태',
  review: '검토하다, 재조사하다',
  contract: '계약(서),계약하다, 수축하다',
  signature: '서명',
  originally: '원래, 처음에는',
  direction: '방향, 지시, 감독',
  initially: '처음에, 초기에',
  expire: '(계약등이)만료되다',
  collaborate: '협력하다, 공동으로 일하다',
  dedicate: '전념하다, 헌신하다, 바치다(indicate 나타내다)',
  revised: '수정된, 변경된',
  imperative: '반드시 해야 하는, 필수적인',
  cooperatively: '협력하여, 협조적으로',
  commission: '수수료, 커미션; 위원회\r\n(일 등을)의뢰하다, 주문하다',
  omit: '빠뜨리다, 생략하다',
  conflict: '대립, 충돌, 갈등',
  renew: '(계약 등을)갱신하다',
  proficient: '능숙한, 능한',
  confidentiality: '기밀, 비밀',
  dispute: '분쟁, 논쟁',
  objection: '반대, 이익',
  define: '규정하다, 정의하다',
  impression: '인상',
  security: '보안, 안전, 보호',
  option: '선택권',
  proceed: '(일을)진행하다, 진척되다',
  modify: '수정하다, 일부 변경하다',
  narrow: '(범위 등을)좁히다',
  bid: '입찰',
  settle: '해결하다, 처리하다',
  terminate: '끝내다, 종결시키다',
  challenging: '도전적인, 힘든',
  foundation: '토대, 기초',
  completely: '전적으로, 완전히',
  refuse: '거절하다',
  temporarily: '일시적으로\r\n(temporary 일시적인, 잠정적인, 임시고용인)',
  dealer: '판매업자, 상인',
  bulk: '대량의',
  inventory: '재고품, 재고목록',
  short: '부족한',
  cost: '비용',
  selection: '선택된 것, 정선품',
  commercial: '상업의, 상업적인, 광고',
  order: '주문하다, 주문, 주문품',
  provide: '공급하다, 제공하다',
  contact: '~와 연락하다,\r\n(상업적 목적으로)교섭하고 있는 사람',
  invoice: '송장',
  move: '옮기다, 움직이다, 조치, 수단;\r\n이동, 이사',
  supply: '공급하다, 공급; (-s)비품, 소모품',
  discount: '할인',
  distribute: '배포하다, 배급하다',
  acquisition: '인수; 구입한 것',
  assure: '~에게 보장하다, ~을 안심시키다, 장담하다',
  subject: '~의 영향을 받기 쉬운;\r\n(동의 등을)조건으로 하는,\r\n~에게(~을) 받게 하다',
  seek: '구하다, 찾다',
  satisfactory: '만족스러운',
  confirmation: '확인, 확증',
  unable: '~할 수 없는',
  payment: '지불(금액),납입(금액)',
  measure: '대책, 조치, 수단\r\n측정하다',
  bargain: '특가품, 흥정',
  stock: '재고; 주식',
  affordability: '감당할 수 있는 비용',
  clientele: '(집합적)고객들,\r\n(변호사,건축가 등의)모든 의뢰인',
  acclaim: '호평, 찬사',
  represent: '~을 대표하다',
  rating: '등급, 평가',
  encompass: '포함하다, 둘러싸다',
  finalize: '마무리 짓다, 완결하다',
  market: '시장',
  retail: '소매',
  commodity: '상품, 산물',
  quote: '견적(액), 견적을 내다',
  consignment: '위탁 판매(consign위탁하다)',
  fragile: '깨지기 쉬운',
  perishable: '부패하기 쉬운',
  deliver: '배달하다; (연설을)하다',
  ensure: '확실하게 하다, 보장하다',
  courier: '급송 택배, 운반인',
  carton: '(큰)판지상자',
  address: '주소,\r\n(어려운 문제 등을)처리하다,다루다',
  shipment: '선적, (화물의)발송;\r\n수송품, 적하물',
  particularly: '특히',
  adequately: '적절히',
  article: '물품, 물건; 기사, 논설',
  efficient: '(기계, 방법 등이)효과적인,능률적인',
  agency: '대행 회사, 대리점',
  enclose: '~을 동봉하다; ~을 둘러싸다, 애워싸다',
  careful: '조심스러운, 주의 깊은',
  'pick up': '~을 찾다; (사람,물건 등을) 도중에 태우다',
  carry: '지니다; (물건을)팔다, 가게에 놓다',
  attach: '붙이다, 접착하다, 첨부하다',
  formerly: '이전에',
  package: '소포, 꾸러미',
  react: '반응하다, 대응하다',
  content: '내용물',
  convenience: '편의, 편리',
  acknowledge: '인정하다; (편지 등의)수령을 알리다, 감사하다',
  caution: '주의, 조심',
  correspondence: '편지, 통신문',
  separate: '분리하다; 분류하다',
  remarkable: '현저한, 두드러진(markedly 현저하게 눈에 띄게)',
  handle: '취급하다, 다루다',
  warehouse: '창고, 저장소',
  impose: '(세금 등을)부과하다',
  storage: '보관소, 저장소',
  detach: '분리하다, 떼다, (attach 붙이다)',
  envelope: '봉투',
  exclusion: '제외, 배제',
  recipient: '수신자',
  affix: '(우표 등을)붙이다',
  incorrect: '부정확한',
  oblige: '어쩔 수 없이 ~하게 하다,\r\n~에게 강요하다',
  step: '단계; 조치, 수단',
  'check in': '체크인하다, 숙박 수속을 하다',
  compensate: '보상하다\r\n(compensation 보상)',
  complimentary: '무료의, 우대의',
  chef: '주방장',
  container: '용기, 그릇',
  elegant: '우아한, 고상한',
  flavor: '맛, 풍미',
  accommodate: '(건물 등이)~을 수용하다, 숙박시키다;(충분한 공간을) 제공하다\r\n(조건, 요구 등을)만족시키다',
  available: '(사물이)이용 가능한;\r\n(사람이) 시간이 있는',
  reception: '환영회; (호텔, 회사, 병원 등의)접수처',
  'in advance': '미리, 사전에',
  refreshments: '다과, 가벼운 음식물',
  make: '~을 하다, ~을 만들다',
  cater: '(연회 등의)음식물을 공급하다',
  reservation: '예약, 지정; 보호구역',
  beverage: '음료',
  confirm: '확인하다',
  cancel: '취소하다',
  rate: '요금',
  conviniently: '편리하게',
  decorate: '장식하다',
  retain: '유지하다, 보유하다',
  atmosphere: '분위기, 환경',
  cuisine: '(독특한)요리',
  sequence: '순서, 차례',
  extensive: '광범위한, 넓은',
  prior: '전의, 먼저의',
  book: '예약하다',
  amenity: '편의 시설',
  belongings: '소지품, 소유물',
  entirely: '완전히',
  ease: '완화시키다, 쉬움, 용이함',
  ingredient: '재료, 성분',
  sip: '음미하며 마시다, 홀짝거리다',
  stir: '휘젓다, 뒤섞다',
  choice: '선택물, 선택 사항, 선택',
  complication: '복잡한 문제',
  freshness: '신선함',
  occupancy: '(호텔등의)이용률',
  decline: '감소, 하락,(초대,신청을)거절하다',
  markedly: '현저하게, 눈에 띄게',
  increase: '인상, 증가, 증가하다',
  revenue: '수입',
  projection: '예상(치)',
  substantial: '상당한',
  anticipate: '예상하다, 기대하다\r\n(anticipation 예상)',
  significantly: '상당히, 두드러지게',
  estimate: '추정하다, 추산하다, 추정(치), 추산',
  shift: '옮기다, 이동하다, 변화, 교대근무',
  fee: '요금, 수수료',
  production: '생산량, 생산',
  sale: '(-s)매출액, 매상고; (할인)판매',
  impressive: '굉장한, 인상적인',
  representative: '직원, 외판원; 대표자',
  recent: '최근의',
  exceed: '~을 초과하다\r\n(exceedingly 대단히, 몹시)\r\n(exceedably 넘을 수 있는)',
  improvement: '향상',
  employer: '고용주',
  regular: '정기적인; 단골의',
  summarize: '요약하다',
  typically: '보통, 일반적으로',
  whole: '전체의, 온전한',
  growth: '성장, 발전',
  figure: '총액, 합계 수',
  steady: '꾸준한; 안정된',
  frequent: '빈번한, 잦은',
  achieve: '달성하다, 성취하다',
  assumption: '추정, 산정, 가정',
  share: '공유하다, 함께쓰다;\r\n(생각, 경험, 감정을 남과)함께 나누다\r\n몫, 지분',
  incur: '(손실을)입다, (빚을)지다',
  slightly: '약간',
  profit: '수익, 이익',
  reliant: '의존하는, 의지하는\r\n(reliantly 의지하여)',
  illustrate: '분명히 보여주다, 설명하다\r\n(illustrate 설명,해설,삽화)',
  inaccurate: '부정확한',
  percentage: '비율, 백분율',
  reduce: '줄이다, 감소시키다',
  tend: '~하는 경향이 있다, ~하기 쉽다',
  audit: '회계 감사, 심사',
  accounting: '회계',
  budget: '예산',
  financial: '재정의, 금전상의',
  curtail: '~을 줄이다, 삭감하다\r\n(curtailment 단축)',
  deficit: '적자, 부족액',
  recently: '최근에',
  substantially: '크게, 상당히\r\n(substantial 상당한, 재력이 있는)',
  committee: '위원회',
  frequently: '자주, 흔히',
  capability: '능력, 역량',
  proceeds: '수익금',
  reimburse: '변제하다, 상환하다',
  considerably: '상당히, 많이',
  adequate: '충분한, 적절한\r\n(adequately 적절히, 충분히)',
  total: '총계의, 전부의',
  allocate: '할당하다, 배분하다\r\n(allocation 할당)',
  inspector: '조사관, 감독관\r\n(inspect 검사하다)',
  preferred: '선호되는, 우선의',
  quarter: '사분기; 4분의1',
  interrupt: '중단시키다, 방해하다\r\n(interruption 방해, 중지, 중단)',
  browse: '흝어보다, 둘러보다',
  prompt: '즉각적인; 신속한, 촉발하다, 유도하다 (promptly 신속히)',
  deduct: '공제하다, 빼다\r\n(deduction 공제)',
  measurement: '측정, 측량; 치수',
  shorten: '단축하다, 짧게하다',
  amend: '수정하다\r\n(amendable 개정할 수 있는)',
  calculate: '계산하다, 산출하다',
  exempt: '면제된, ~이 없는\r\n(exemption 면제)',
  deficient: '부족한, 불충분한',
  compare: '비교하다',
  fortunate: '운 좋은',
  expenditure: '지출, 비용',
  accurately: '정확하게',
  worth: '~의 가치가 있는, (얼마)어치, 가치',
  excess: '초과, 초과량',
  fiscal: '회계의, 재정상의',
  incidental: '부수적인',
  inflation: '물가상승, 인플레이션, 통화팽창',
  liable: '책임져야 할; ~하기 쉬운',
  spend: '~을 쓰다, 소비하다',
  turnover: '총 매상고, 거래액; 이직률',
  announce: '발표하다',
  interested: '관련 있는; 관심이 있는',
  active: '적극적인, 활발한',
  accept: '수락하다, 승낙하다',
  foresee: '예견하다, 예감하다',
  expansion: '확장, 팽창',
  relocate: '(공장 등을)이전하다',
  competitor: '경쟁업체, 경쟁자',
  asset: '자산',
  contribute: '기여하다, 공헌하다',
  dedicated: '(목표 등에)전념하는, 헌신적인',
  misplace: '잃어버리다, 위치를 잘못 잡다',
  considerable: '(정도나 양이)상당한',
  last: '지속되다',
  emerge: '부상하다, 나타나다\r\n(merge 합병하다)',
  grow: '성장하다, 성장시키다, 증가시키다',
  select: '선발하다, 선택하다',
  merge: '합병하다, 병합하다',
  imply: '암시하다, 넌지시 나타내다, 의미하다',
  vital: '필수적인',
  persist: '(집요하게)계속하다, 계속되다, 지속되다\r\n(continue 계속되다, 계속하다)',
  independent: '독립적인, 독자적인',
  force: '세력',
  establish: '설립하다',
  initiate: '(사업 등을) 착수하다, 시작하다\r\n(commence 시작하다)',
  enhance: '(질 등을) 향상시키다, 높이다, 강화하다\r\n(strengthen 강화하다)\r\n(reinforce 보강하다, 강화하다)',
  renowned: '저명한, 유명한, 명성이 있는',
  informed: '정보에 근거한\r\n(inform 알리다, 통지하다)',
  minutes: '회의록',
  waive: '(규칙 등을)적용하지 않다,\r\n(권리,청구등을)포기하다\r\n(abandon 버리다, 단념하다, 그만두다)',
  reach: '(치수,양 등이)~에 달하다;\r\n~에 도착하다',
  authority: '권한; 당국',
  acquire: '매입하다, 취득하다\r\n(inquire 묻다)\r\n(inquiry 조사, 문의)',
  surpass: '~을 능가하다, 넘어서다',
  run: '~을 운영하다, 경영하다',
  improbable: '사실이라고 생각할 수 없는,\r\n일어날 것 같지 않은\r\n(probable 있음직한, 일어날것같은)',
  edge: '우위, 유리함; 가장자리, 끝',
  simultaneously: '동시에\r\n(coincidentally 우연히 일치하게 동시발생적으로)',
  reveal: '밝히다, 누설하다',
  productivity: '생산성',
  uncertain: '확신이 없는, 불확실한',
  premier: '으뜸의, 첫째의',
  agenda: '의제, 의사일정',
  convene: '(회원 등이)모이다, (회의가)개최되다\r\n(convener 의장,소집자)',
  refute: '부인하다, 반박하다\r\n(refutation 반박, 반론)',
  coordination: '조정',
  unanimous: '만장일치의, 동의하는\r\n(unanimously  만장일치로)',
  convince: '납득시키다, 확신시키다',
  consensus: '여론, 일치된 의견',
  defer: '연기하다, 미루다\r\n(differ 다르다)',
  usually: '보통, 일반적으로',
  reschedule: '일정을 바꾸다',
  meeting: '회의',
  determine: '알아내다; 결정하다, 확정하다',
  report: '보고하다; 출두하다,\r\n(직장,회의 등에 도착을)알리다,\r\n보고서; 보도, 기록',
  comment: '논평하다, 언급하다',
  phase: '단계',
  approve: '승인하다, 찬성하다',
  enclosed: '동봉된',
  easy: '쉬운, 용이한',
  record: '기록; 경력, 이력, 기록하다',
  suggestion: '제안',
  attention: '주의, 경청',
  object: '반대하다',
  coincidentally: '우연히, 일치하게, 동시 발생적으로\r\n(coincident 일치하는)',
  crowded: '붐비는, 복잡한',
  undergo: '겪다, 거치다, 경험하다',
  outcome: '결과 (=consequence)',
  narrowly: '주의 깊게, 좁게; 가까스로, 간신히, 겨우',
  differ: '의견을 달리하다, 다르다',
  discuss: '논의하다, 토론하다',
  give: '(연설, 수업 등을)하다',
  brief: '~에게 간단히 설명하다, 브리핑하다',
  distract: '(주의를)산만하게 하다, 빗기게 하다(distraction 주의산만, 방심)',
  emphasis: '강조, 중점',
  press: '언론(계),보도기관, 누르다',
  organize: '준비하다, 조직하다, 정리하다',
  mention: '언급하다',
  persuasive: '설득력 있는',
  understanding: '이해심 있는',
  adjourn: '(회의 등을)휴회하다',
  constructive: '건설적인',
  preside: '(회의의)사회를 보다, ~의 의장을 맡아보다',
  irrelevant: '관계가 없는, 무관한\r\n(relevant 관계가 있는)',
  constraint: '제한(=restriction)',
  host: '(대회 등을)주최하다',
  annual: '매년의',
  purpose: '목적, 의도',
  enroll: '등록하다',
  lecture: '강의, 강연',
  participant: '참가자',
  attend: '참석하다, 출석하다',
  encourage: '장려하다, 복돋아주다',
  leave: '휴가, 떠나다, 남기다',
  recommendation: '추천사항, 추천',
  conference: '회의, 회담',
  schedule: '~을 예정하다',
  include: '포함하다',
  result: '결과,(~의 결과로)되다',
  register: '등록하다',
  require: '요구하다',
  grateful: '고마워하는, 감사하는',
  overtime: '초과근무, 야근',
  responsibility: '부담, 책임, 의무',
  assent: '찬성하다, 승인, 동의\r\n(approval 승인)\r\n(approve 찬성하다)\r\n(prove 증명하다)',
  regard: '~을 -으로 간주하다, 여기다,\r\n관심,배려',
  tentative: '임시적인, 잠정적인',
  welcome: '반가운, 기꺼이 받아들여지는',
  function: '행사, 연회',
  commence: '시작되다',
  objective: '목표, 목적',
  excited: '신이 난, 들뜬',
  reimbursement: '상환, 변제, 배상',
  treatment: '대우, 처우',
  honor: '존경, 명예',
  emphasize: '강조하다',
  entry: '(경기 등의)참가자, 출품물',
  bonus: '상여금, 보너스',
  salary: '급여',
  earn: '(금전 등을)벌다; (평판을)받다, 얻다',
  arise: '(문제 등이)발생하다, 일어나다 = occur',
  labor: '노동',
  union: '노동조합',
  existing: '기존의, 현행의',
  exploit: '착취하다, 부당하게 이용하다\r\n(exploitation 개발,개척,약탈,착취)',
  appoint: '임명하다, 지명하다',
  appraisal: '평가',
  promote: '승진시키다; 촉진하다',
  skilled: '숙련된, 노련한',
  radically: '완전히, 철저히, 근본적으로\r\n(radical 근본적인, 과격한)',
  exceptional: '뛰어난, 예외적인\r\n(exception 예외, 이의, 반대)',
  appreciation: '감사',
  evaluate: '평가하다',
  suggest: '제안하다, 추천하다',
  preference: '선호',
  management: '경영진, 경영',
  predict: '예측하다',
  transfer: '보내다; 전근시키다',
  award: '상\r\n(reward 보상하다, 포상,보상)',
  mandatory: '의무적인',
  competent: '유능한, 능숙한\r\n(competence 능력)',
  performance: '실적,성과; 공연,연주, 연기',
  reward: '~에 보답하다, 보상하다, 포상,보상\r\n(award 상)',
  search: '찾기, 수색, 조사',
  inexperienced: '경험없는, 미숙한',
  early: '시간상 이른, 조기의',
  designate: '지명하다, 지정하다',
  executive: '경영의,관리의',
  dedication: '헌신',
  unanimously: '만장일치로\r\n(unanimous 만장일치의)\r\n(anonymously 익명으로, 특색없이)',
  progress: '진행, 진척, 진전, 진보하다, 발전하다',
  congratulate: '축하하다',
  dismiss: '해임하다, 해고하다',
  independence: '독립성',
  participation: '참여, 참가, 가입',
  praise: '칭찬',
  accomplishment: '성과,업적',
  deliberation: '토의, 심의, 숙고\r\n(deliberate 고의의, 숙고하다)',
  leadership: '리더십, 지도력',
  retire: '퇴직하다, 은퇴하다',
  nomination: '임명, 지명',
  reorganize: '재편성하다, 재조직하다\r\n(recognize 인식하다)\r\n(organize 조직하다)',
  serve: '근무하다, 일하다',
  encouragement: '격려',
  resignation: '사임, 사직, 사직서',
  strictly: '엄격히',
  congestion: '(교통의)체증, 혼잡\r\n(congest 혼잡하게 하다)',
  alleviate: '완화하다',
  divert: '우회시키다, 다른 곳으로 돌리다',
  detour: '우회',
  fuel: '연료',
  malfunction: '오작동, 기능불량',
  permit: '허락하다, 허가증',
  transportation: '교통(수단), 운송 수단',
  opportunity: '기회',
  clearly: '명확히',
  ongoing: '계속 진행 중인',
  detailed: '상세한',
  alternative: '대안, 대체, 다른, 대신의',
  obtain: '획득하다, 얻다',
  designated: '지정된',
  intersection: '교차로, 교차지점',
  equip: '갖추다, 설비하다',
  commute: '통근하다',
  downtown: '시내에서, 도심지로',
  automotive: '자동차의',
  closure: '폐쇄',
  vehicle: '차량, 운송 수단',
  platform: '승강장',
  official: '공무원, 관리, 공식적인',
  transit: '교통, 수송, 통과하다',
  fare: '교통요금',
  expense: '비용, 지출',
  trust: '신뢰, 신임, 믿다, 신뢰하다',
  head: '(~의 방향으로)나아가다, 향하게 하다',
  drive: '(차 등을)운전하다, 타고가다, 조종하다',
  fine: '벌금',
  pass: '지나가다, 통과하다',
  securely: '(매듭 등이)단단하게, 튼튼하게',
  prominently: '눈에 잘 띄게, 두드러지게\r\n(prominent 눈에 띄는)',
  reserved: '예약된, 예약한; 지정된',
  average: '평균치, 평균',
  collision: '충돌',
  tow: '견인하다',
  reverse: '뒤의, 반대의',
  obstruct: '(전망 등을)가리다, 차단하다;\r\n(도로 등을)막다\r\n(obstruction 장애물, 방해물)',
  delinquent: '(세금 등이)연체된, 미불의',
  overdue: '(지불,반납 등의)기한이 지난, 지불 기한이 넘은',
  regrettably: '유감스럽게도',
  balance: '잔고, 차감 잔액',
  deposit: '입금하다, 예금하다',
  investigation: '조사 (investigate 연구하다, 조사하다)',
  account: '계좌; 설명; 고려',
  statement: '명세서, 성명서',
  amount: '액수, 양',
  withdrawal: '(예금의)인출',
  previously: '이전에',
  due: '만기가 된, 지불 기일이 된;\r\n(금전 등이)~에게 마땅히 지급되어야 할',
  receive: '받다, 수취하다',
  expect: '예상하다, 기대하다',
  certificate: '증명서, 증서',
  document: '서류, 문서',
  spending: '소비; 지출',
  successfully: '성공적으로',
  bill: '~에게 청구서를 보내다, 청구서, 계산서',
  pleasure: '즐거움, 기쁜, 영광',
  study: '연구',
  summary: '요약, 개요\r\n(emphasize 강조하다)',
  temporary: '임시의',
  lower: '(양,가격을)줄이다',
  transaction: '거래, 업무',
  double: '두배로 만들다',
  identification: '신분증, 신분 증명서',
  dissatisfaction: '불만, 불평',
  'in common': '공통으로, 공동으로',
  interest: '관심; 권리; 이자',
  reject: '거절하다, 거부하다',
  relation: '관계',
  tentatively: '임시로, 시험적으로\r\n(tentative 시험적인, 임시의, 가설)',
  alternatively: '그렇지 않으면, 그 대신에',
  attentive: '주의 깊은, 세심한',
  convert: '전환하다, 변환하다',
  heavily: '몹시, 심하게',
  loan: '대출, 대출금',
  unexpected: '예기치 않은',
  cash: '현금으로 바꾸다',
  mortgage: '(담보)대출',
  payable: '지불해야 하는',
  personal: '개인의',
  investment: '투자, 투자금',
  incrative: '수익성 있는, 돈벌이가 되는\r\n(profit, earning, gainings 이익)\r\n(income 수입, 소득)',
  inherently: '본질적으로\r\n(inherent 본래 갖추어져 있는, 고유의)',
  secure: '확보하다, 얻어 내다;\r\n안전하게 지키다, 고정시키다',
  foreseeable: '예견할 수 있는\r\n(oversee 감독하다)\r\n(overseas 외국의)',
  innate: '타고난',
  property: '재산',
  'on behalf of': '~을 대신해서',
  lease: '임대차(계약)',
  sponsor: '후원하다, 후원자',
  propose: '제안하다',
  support: '후원, 원조, 지지, 지원하다,\r\n후원하다; 살게하다,\r\n(생명, 기력 등을)유지하다',
  distributuion: '분배, 배급',
  consider: '고려하다',
  nearly: '거의, 대략',
  consent: '동의, 허락, 동의하다\r\n(consentaneous일치하는)',
  gratitude: '고마움, 감사',
  consult: '상의하다, 상담하다',
  advice: '조언, 충고',
  partially: '부분적으로, 일부분은',
  evident: '분명한, 명백한,',
  reliability: '신뢰도, 믿음직함',
  cautious: '조심하는, 신중한',
  insight: '식견, 통찰력',
  portfolio: '포트폴리오, 투자 자산 구성',
  possible: '가능한, 있음직한',
  speculation: '추측\r\n(speculate, suppose, guess, infer 추측하다)',
  solely: '오로지, 혼자서, 전적으로',
  entrepreneur: '사업가',
  eventually: '결국, 마침내',
  shareholder: '주주',
  outlook: '전망',
  stability: '안정, 안정성',
  bond: '채권',
  depreciation: '가치 하락, 화폐의 구매력 저하\r\n(depreciate : ~의 가치를 떨어뜨리다, 가치가 떨어지다)',
  increasing: '증가하는',
  prevalent: '유행하고 있는, 널리 퍼진\r\n(prevalence 보급, 유행)',
  rapid: '빠른, 신속한',
  unprecedented: '전례 없는\r\n(precedented 전례가 있는)',
  yield: '(이윤을) 가져오다, 산출하다',
  furnished: '가구가 비치된',
  residence: '거주지, 주택',
  spacious: '(공간이)넓은',
  drape: '(방 등을 커튼 등으로)장식하다',
  unoccupied: '(집 등이)비어 있는, 사람이 살지 않는\r\n(occupy 차지하다, 점유하다)',
  renovation: '수리, 개조',
  appropriate: '적당한, 적합한(appropriately 적합하게)',
  delay: '연기하다, ~을 뒤로 미루다',
  community: '지역 사회, 공동체',
  construction: '건설, 건축',
  repair: '수리하다',
  currently: '현재',
  regularly: '정기적으로',
  arrange: '배열하다, 정돈하다',
  location: '장소, 위치',
  restore: '복구하다, 회복시키다\r\n(recovery 회복, recover되찾다, 회복하다)',
  presently: '현재\r\n(present, current현재의)\r\n(latest, recent, up to date 최근의)',
  numerous: '많은',
  abandon: '그만두다; 버리다(abondonment 버림, 포기)',
  contractor: '계약자, 도급업자',
  develop: '개발하다',
  maintain: '유지하다, 관리하다',
  densely: '빽빽이, 밀집하여',
  prepare: '준비하다, 채비를 갖추다',
  finally: '결국, 마침내',
  district: '지역, 지구',
  renewal: '재개발',
  compulsory: '의무적인',
  interfere: '방해하다, 해치다',
  relocation: '이전, 재배치',
  totally: '완전히, 전적으로',
  actually: '실제로, 사실은',
  architect: '건축가',
  enlarge: '확장하다, 확대하다',
  install: '설치하다, 장치하다',
  permanent: '영구적인',
  suppose: '생각하다, 추측하다(guess, infer 추측하다)',
  adjacent: '인접한',
  consist: '구성되다, 이루어지다',
  utility: '공공시설; 공공요금',
  conserve: '보전하다, 유지하다',
  chance: '가능성, 기회',
  forecast: '(날씨의)예보',
  waste: '쓰레기, 폐기물',
  dispose: '처분하다, 처리하다',
  recycling: '재활용',
  clear: '맑게 갠; 명백한, 분명한\r\n또렷하게, 완전히; 떨어져서',
  damage: '피해, 손해, 손상시키다',
  significant: '상당한; 중대한, 중요한',
  solution: '해결책',
  occur: '(일이)발생하다, 생기다(happen, take place)',
  ideal: '이상적인',
  preserve: '보존하다, 보호하다(=conserve, maintain, retain, keep)',
  aid: '원조, 돕다',
  excessive: '지나친, 과도한(excess 초과, 초과량)',
  intensively: '집중적으로( intense 격렬한)',
  vary: '다르다, 다양하다',
  pleasing: '즐거운, 기분 좋은, 만족스러운',
  mark: '점수, 평점, 표시, 축하하다',
  inaccessible: '접근이 불가능한, 이용이 불가능한',
  disturb: '방해하다',
  pollutant: '오염물질',
  emission: '배기가스, 방출',
  dense: '빽빽한, 밀집한',
  environmental: '환경적인',
  consistent: '일치하는, 지속적인, 한결같은',
  leak: '누출, 누출량',
  organization: '단체',
  continually: '계속해서',
  contaminate: '오염시키다(=pollution)',
  disaster: '재난',
  discharge: '방출하다',
  resource: '자원, 자료',
  prominent: '유명한, 두드러진',
  deplete: '고갈시키다(depletion 고갈)',
  purify: '정화시키다',
  endangered: '멸종 위기에 처한',
  extinction: '멸종',
  drought: '가뭄',
  inflict: '(고통,피해를)입히다, 가하다',
  migration: '이동, 이주',
  ecology: '생태, 자연환경',
  habitat: '(동, 식물의)서식지',
  fatigue: '피로',
  checkup: '건강 진단',
  symtom: '증상',
  physician: '내과의사',
  diagnosis: '진단',
  prescribe: '(약을)처방하다, 규정하다',
  recovery: '회복, 쾌유',
  recognize: '인정하다, 알아보다\r\n(organize 조직하다)',
  join: '~에 가입하다',
  comprehensive: '종합적인, 포괄적인',
  participate: '참여하다, 참가하다',
  recommend: '권고하다, 추천하다',
  necessary: '필요한',
  ability: '능력',
  operation: '수술',
  cleanliness: '청결',
  duration: '지속 기간, 지속',
  examination: '진찰, 검사',
  eliminate: '제거하다(elimination 제거)',
  easily: '쉽게',
  dental: '치과의',
  dietary: '식이 요법의, 규정식의',
  related: '관련된',
  transmit: '전염시키다(transmittable 전염가능한, 유전가능한)',
  periodically: '주기적으로',
  reaction: '반응',
  simple: '단순한',
  coverage: '(보험의)보상 범위; (신문 등의)보도, 취재범위',
  exposure: '노출',
  pharmaceutical: '제약의, 약학의',
  premium: '보험료',
  relieve: '완화시키다',
  combination: '결합, 연합',
  conscious: '알고 있는, 자각하고 있는\r\n(consciousness : 의식)',
  deprivation: '박탈, 상실(deprivative 박탈하는, 빼앗는)',
  health: '건강; (사회,기관의,)번영,안녕',
  induce: '유발하다 (reduce줄이다, 낮추다)',
  insurance: '보험',
  nutrition: '영양',
  prevention: '예방(prevent 예방하다, 방해하다)',
  susceptible: '~에 감염되기 쉬운, 영향 받기 쉬운' };